---
template_path: ec2/instance.yaml.j2

sceptre_user_data:
  project_code: "{{ stack_group_config.project_code }}"
  source_repo_url: !environment_variable SOURCE_REPO_URL
  source_repo_branch: !environment_variable SOURCE_REPO_BRANCH
  instances:
    - name: TestStation
      creation_policy:
        resource_signal:
          count: 1
          timeout: PT5M
      image_id: !rcmd echo -n $(helper-scripts/get-ami-id.sh)
      iam_instance_profile: !stack_output "{{pwd}}/iam-instanceprofile.yaml::GenericInstanceRole"
      instance_type: t3a.micro
      block_device_mappings:
        - device_name: /dev/xvda
          ebs:
            delete_on_termination: true
            volume_size: 20
            volume_type: gp3
            encrypted: true

      network_interfaces:
        - associate_public_ip_address: true
          delete_on_termination: true
          description: Primary network interface
          device_index: "0"
          group_set:
            - !stack_output {{pwd}}/ec2-securitygroup.yaml::TestStationInstanceSG
          subnet_id: !stack_output_external vpcdemo-demo02a-ec2-subnet::SubnetPrivateA
      tags:
        Name: TestStation
        Project: {{ stack_group_config.project_code }}
      metadata: |
        AWS::CloudFormation::Init:
          configSets:
            default:
              - cfn_hup
              - cfn_update
            configset_update:
              - cfn_update
          cfn_hup:
            files:
              /etc/cfn/cfn-hup.conf:
                content:
                  Fn::Sub: |
                    [main]
                    stack=${AWS::StackId}
                    region=${AWS::Region}
                    umask=022
                    interval=2
                mode: "000400"
                owner: root
                group: root
                encoding: plain
              /etc/cfn/hooks.d/cfn-auto-reloader.conf:
                content:
                  "Fn::Sub": |
                    [cfn-auto-reloader-hook]
                    triggers=post.update
                    path=Resources.TestStation.Metadata.AWS::CloudFormation::Init
                    action=/opt/aws/bin/cfn-init -v --stack ${AWS::StackName} --resource TestStation --configsets configset_update --region ${AWS::Region}
                    runas=root
                mode: "000400"
                owner: root
                group: root
                encoding: plain
            packages:
              yum:
                jq: []
            services:
              sysvinit:
                cfn-hup:
                  enabled: "true"
                  ensureRunning: "true"
                  files:
                    - /etc/cfn/cfn-hup.conf
                    - /etc/cfn/hooks.d/cfn-auto-reloader.conf
          cfn_update:
            files:
              /root/fox.txt:
                content: |
                  The quick brown fox jumps over the lazy dog.
                encoding: plain
                owner: root
                group: root
                mode: '000644'
      user_data: |
        Fn::Base64:
          Fn::Sub: |
            #!/bin/bash -xe
            # Initialize the system using instructions from metadata
            /opt/aws/bin/cfn-init \
              --stack ${AWS::StackName} \
              --resource TestStation \
              --region ${AWS::Region} \
              --configsets default \
              --verbose
            # Signal the status from cfn-init
            /opt/aws/bin/cfn-signal -e $? \
              --stack ${AWS::StackName} \
              --resource TestStation \
              --region ${AWS::Region}
