---
template:
  path: iam/instance_profile.yaml.j2

sceptre_user_data:
  project_code: "{{stack_group_config.project_code}}"
  source_repo_url: "{{stack_group_config.source_repo_url}}"
  instance_profiles:
    - name: GenericInstanceRole
      role_name: !stack_output "{{pwd}}/iam-role.yaml::GenericInstanceRole"
