---
template_path: iam/role.yaml.j2

sceptre_user_data:
  project_code: "{{stack_group_config.project_code}}"
  source_repo_url: "{{stack_group_config.source_repo_url}}"
  roles:
    - name: GenericInstanceRole
      assume_role_policy_document: |
        Version: "2012-10-17"
        Statement:
          - Effect: Allow
            Principal:
              Service:
              - ec2.amazonaws.com
            Action:
              - 'sts:AssumeRole'
      description: IAM Role for Generic EC2 Instance
      managed_policy_arns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
        - arn:aws:iam::aws:policy/AWSCloudFormationReadOnlyAccess
        - arn:aws:iam::aws:policy/AmazonSSMDirectoryServiceAccess
      policies:
        - policy_name: S3access
          policy_document: |
            Version: 2012-10-17
            Statement:
              - Sid: AllowBucketLevelAccess
                Effect: Allow
                Resource:
                  - '*'
                Action:
                  - s3:ListBucket
                  - s3:ListBucketMultipartUploads
              - Sid: AllowObjectLevelAccess
                Effect: Allow
                Resource:
                  - '*'
                Action:
                  - s3:PutObject
                  - s3:PutObjectAcl
                  - s3:PutObjectRetention
                  - s3:PutObjectTagging
                  - s3:PutObjectVersionAcl
                  - s3:PutObjectVersionTagging
                  - s3:DeleteObject
                  - s3:DeleteObjectTagging
                  - s3:DeleteObjectVersion
                  - s3:DeleteObjectVersionTagging
                  - s3:GetObject
                  - s3:GetObjectAcl
                  - s3:GetObjectTagging
                  - s3:GetObjectVersion
                  - s3:GetObjectVersionAcl
                  - s3:GetObjectVersionTagging
                  - s3:ListMultipartUploadParts
                  - s3:AbortMultipartUpload
      max_session_duration: 3600
      tags:
        Name: GenericInstanceRole
        Project: {{stack_group_config.project_code}}
